### ISSUE TITLE
eventParticipation table changes

### ISSUE THREAD

**Issue by higginsAmy** [higginsAmy/CS341project#10]
Proposed change to one column in eventParticipation that will affect a lot of things.  If we change the column 'user' to 'userId', we can store the integer associated with the user instead of the username, therefore if the username is changed in the user table, it does not affect the eventParticipation table.  This change comes along with modifying the display of the calendar and possibly the session variable stored because currently most queries use 'username' instead of 'userId'.  This is a major overhaul, but it makes sense if we're going to make it an option to change the username.

**Comment by higginsAmy** [comment]
I meant this issue to be also a change to the eventParticipation so that instead of storing the username it stores the userId.  That in turn changes a lot of things.  Just changing the query is not what I intended this issue to be.  It's like we discussed, if the eventParticipation table stores a user's id instead of the username, the username can be changed with no issues.

**Comment by ChangsongLi** [comment]
I did what you said. I don't know what are you talking about.

**Comment by ChangsongLi** [comment]
Right now, eventParticipation table store user's id instead of the username on my machine. And I pushed it.

**Comment by ChangsongLi** [comment]
It didn't work on your machine? My eventParticipation looks like this

id   eventId user type
215 19  10  S

**Comment by higginsAmy** [comment]
So you didn't alter the table at all? It was storing username as a string. It should be storing user id as an integer. In order for it to be parsed correctly everywhere else there needs to be changes made to the table. If you make the changes, could you push to the repository a new copy of the database or tell us what the updated field will be called?
- Amy Higgins

**Comment by ChangsongLi** [comment]
Oh, I got it. I could push the newest database. I will only change the type of "user in the eventParticipation table" from TEXT to INT, and I won't change the field's name. Also, I have been changed the username in the User table to be unique. Therefore, the username change.php will work properly. I will push it right now.
