### ISSUE TITLE
modifyEvent show signups

### ISSUE THREAD

**Issue by higginsAmy** [higginsAmy/CS341project#13]
In event view pane, show how many volunteers and students are signed up (admin, volunteer).  The assumption we'd add there is that the volunteer/admin cancels class if minimum student threshold is not met by one week beforehand.

**Comment by AdamGeipel** [comment]
What pages exactly will we have to change? I'm assuming just Volunteer.php and Admin.php, but I don't know what exactly you added to make the events clickable.

**Comment by AdamGeipel** [comment]
I believe that as a result of this, the headings of the list and the columns are out of alignment. Needs to be fixed (see issue 22)
