### ISSUE TITLE
Contacts/Donate pages

### ISSUE THREAD

**Issue by higginsAmy** [higginsAmy/CS341project#17]
No need for them to be functional, we just need to fill them in as placeholders for the final product since they were part of our initial specs.  The contacts page can have real addresses and phone numbers, or fake ones, or any combination of real and fake data.  The donate page can have a form (maybe?) with a place for name and amount, and a button that brings up an alert saying that they will be redirected to paypal to process, or something like, "donations can be made to paypal account 'HolmenRobotics'" or something like that.  I'm open to ideas.

**Comment by AdamGeipel** [comment]
In case we wanted to add paypal buttons:
https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donation_buttons/

**Comment by AdamGeipel** [comment]
Donate page is done if you want to take a look. May need some polish, I'd like to get the button centered under the text but don't know how ¯\_(ツ)_/¯
