### ISSUE TITLE
Dummy-proof newEvent

### ISSUE THREAD

**Issue by higginsAmy** [higginsAmy/CS341project#5]
Dummy-proof this form so users can't enter bad data.  Tasks include: 1) Check if date exists - possibly exclusively using date picker, otherwise validating form data before submitting. 2) Check if times are valid - preferably using dropdown with values 1-12 for hour, 15-minute increments for minutes, and AM/PM. Also check that start date/time is before end date/time.  3) Make sure minVol maxVol minStud maxStud are integers upon form submission before insert query.  4) Event addition check - only in future, not in past.

**Comment by ChangsongLi** [comment]
I'm gonna try to do this.
